"""empty message

Revision ID: eaf714198f1f
Revises: 8108bfea6e4e
Create Date: 2022-08-10 15:14:21.772376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf714198f1f'
down_revision = '8108bfea6e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('avail_from', sa.DateTime(), nullable=True))
    op.add_column('artists', sa.Column('avail_to', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'avail_to')
    op.drop_column('artists', 'avail_from')
    # ### end Alembic commands ###
