"""empty message

Revision ID: fbbe2db2afe0
Revises: eaf714198f1f
Create Date: 2022-08-12 00:34:41.508654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbbe2db2afe0'
down_revision = 'eaf714198f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artists', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artists', type_='unique')
    # ### end Alembic commands ###
